stm32f4xx-hal = { git = "https://github.com/stm32-rs/stm32f4xx-hal", features = ["rt", "stm32f407"] }
# cortex-m-rt = { version = "*", features = ["device"] }
cortex-m-rtic = "*"
cortex-m = "*"
cortex-m-semihosting = "*"
panic-semihosting = { version = "*", features = ["exit"] }

[profile.release]
opt-level = 'z'
lto = true
debug = true
